import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Navbar from "../component/navbar/Navbar";
import styles from "../styles/Home.module.css";
import Footer from "../component/footer/Footer";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sam Wilk Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo itaque
          voluptatem voluptas sed nostrum velit illum, corporis voluptate enim
          soluta ullam, incidunt suscipit reprehenderit tempore fugiat! Magni
          corrupti laborum placeat.
        </h1>
      </main>
    </div>
  );
};

export default Home;
