import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Navbar from '../component/navbar/Navbar'
import styles from '../styles/Home.module.css'
import Footer from '../component/footer/footer'


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sam's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Sam Wilk's Portfolio Page
        </h1>

      </main>

      <Footer />
    </div>
  )
}

export default Home
