import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Navbar from "../component/navbar/Navbar";
import styles from "../styles/Home.module.css";
import Footer from "../component/footer/Footer";

const Home: NextPage = () => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Sam Wilk Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>Sam Wilk</h1>
          <h3 className={styles.describe}>
            Computer Science Student | University of North Florida
          </h3>
          <h3 className={styles.describe}>Front End Developer</h3>
        </main>
        <div className={styles.Photo}>
          <Image src="/Jax.jpeg" width={1140} height={800} layout="fill" />
        </div>
      </div>
    </>
  );
};

export default Home;
